### ISSUE TITLE
Certificate.ps1

### ISSUE THREAD

**Issue by poojabaligide** [J0F3/PowerShell#7]
After the execution of the script, the certificate is getting installed and we can see manually in the MMC console , but not able export it and located export path

**Comment by poojabaligide** [comment]
the export task is not happening, and it is not going in to the below loop:
if ($export) {
            Write-Debug "export parameter is set. => export certificate"
            Write-Verbose "exporting certificate and private key"
            $cert = Get-Childitem "cert:\LocalMachine\My" | where-object {$_.Thumbprint -eq (New-Object System.Security.Cryptography.X509Certificates.X509Certificate2((Get-Item $cer).FullName, "")).Thumbprint}
            Write-Debug "Certificate found in computerstore: $cert"

            #create a pfx export as a byte array
            if($Password) {
                Write-Debug "Exporting with password"
                $certbytes = $cert.export([System.Security.Cryptography.X509Certificates.X509ContentType]::pfx, $Password)
            }  else {
                Write-Debug "Exporting without password"
                $certbytes = $cert.export([System.Security.Cryptography.X509Certificates.X509ContentType]::pfx)
            }
            

            #write pfx file
            if ($PSBoundParameters.ContainsKey('ExportPath')) {
                $pfxPath = Join-Path -Path (Resolve-Path -Path $ExportPath) -ChildPath "$CN.pfx" 
            }
            else {
                $pfxPath = ".\$CN.pfx"
            }
            $certbytes | Set-Content -Encoding Byte -Path $pfxPath -ea Stop
            Write-Host "Certificate successfully exported to `"$pfxPath`"!" -ForegroundColor Green
		    
            Write-Verbose "deleting exported certificate from computer store"
            # delete certificate from computer store
            $certstore = new-object system.security.cryptography.x509certificates.x509Store('My', 'LocalMachine')
            $certstore.Open('ReadWrite')
            $certstore.Remove($cert)
            $certstore.close() 
		    
        }

**Comment by J0F3** [comment]
Can you please provide me the full command that you run?

Note that the script as two "modes" in which it can operate. One where the certificate get requested an installed in the local computer cert store and one where the certificate is exported and removed from the cert store. 

You define by the ```-export``` parameter which "mode" is used. If ```-export``` is not specified the script will skip the export operation completely.

Thx
Jonas

**Comment by poojabaligide** [comment]
Thank you so much , its working by giving the export parameter

**Comment by poojabaligide** [comment]
on which all powershell version the script will run..? is it specifically to run on powershell version 5?

**Comment by J0F3** [comment]
I tested/used the script only on PowerShell 5.1 (WMF 5.1). It will maybe also run also on PowerShell core (6) but not sure/tested.
But foremost it heavily depends on certreq.exe as the actual certificate handling is made by using the certreq.exe. It is therefore for sure not cross platform compatible and will run only on Windows anyway.

**Comment by poojabaligide** [comment]
I tested the script in powershell version 5, and it is working..when the same script is testing with version 4 it's not working.. could you please tell me what are the prerequisites for this script

**Comment by J0F3** [comment]
Can you post here the error message which you get on Version 4? 

Initially the Script was even developed on Version 2. So the chances are very high it will work also on lower version than 5.1 but, as said, I have tested it only on 5.1 and can not say what happens on lower version.

However if you still on version 4 I would really recommend you to upgrade to 5.1 by installing the WMF 5.1.

Thx

**Comment by poojabaligide** [comment]
giving below error ,: Powershell version is 4

C:\Users\Administrator\Desktop\cert_new.ps1 : Method invocation failed because [System.DirectoryServices.DirectorySearcher] does not contain a method named 'new'.
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,cert_new.ps1

**Comment by J0F3** [comment]
This seems the same as #9 and as mentioned there you can you the `-CAName` parameter to workaround this error.

Which Windows version are you running? Can you test if the problem still exists if you update to PowerShell 5.1?

**Comment by poojabaligide** [comment]
still the problem exists, the client is not ready to upgrade the version as it dependent.and which dot.net frame work is Mandatory for this script? and is it compulsory to have certreq.exe file?

**Comment by poojabaligide** [comment]
I tested the same script with powershell version 4 , it able to generate certificate....but I have commented the [ new method line in script] .so it will prompt for choosing CA template manually

**Comment by J0F3** [comment]
Yes, the script will actually work without these lines. The function of these is just to search in the Active Directory for an Enterprise CA if not one is explicit specified with the `-CAName` parameter...

So I am going to close that as you have apparently found a workaround.

Thx
