### ISSUE TITLE
certificate.ps1- CA Template Name not found

### ISSUE THREAD

**Issue by poojabaligide** [J0F3/PowerShell#8]
During Execution of script, we are  getting the below error : 

Template Name not found . 

But are having the template name as EX : xxxx Web Server .

Kindly help .

**Comment by J0F3** [comment]
The name which the scripts needs is the 'common name' of the template which never have spaces in it. 'xxxx Web Server' seems to be the friendly name. So try 'xxxxWebServer' as template name.

You can get the actual common name of your template with `certutil -Template` also.

Hope this helps.

Thx
Jonas

**Comment by poojabaligide** [comment]
thank you for your reply , and wish you a happy new year.  Still testing is pending . I will update once it is done
