### ISSUE TITLE
Method invocation failed because [System.DirectoryServices.DirectorySearcher] does not contain a method named 'new'

### ISSUE THREAD

**Issue by poojabaligide** [J0F3/PowerShell#9]
# $CAs = [System.DirectoryServices.DirectorySearcher]:: new($searchBase,'objectClass=pKIEnrollmentService').FindAll()#

This command is giving below error , 

C:\Users\Administrator\Desktop\cert_new.ps1 : Method invocation failed because [System.DirectoryServices.DirectorySearcher] does not contain a method named 'new'.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,cert_new.ps1

**Comment by J0F3** [comment]
Hmm, that's strange. System.DirectoryServices.DirectorySearcher is actually part of .NET.
Could you please give me some more details about your setup?
- On which Windows Version do you run the script?
- What is the PowerShell version which are you using (check whit `get-host`)?

You can also overcome this error by providing you CA name explicit whit the `-CAName` parameter. Then the System.DirectoryServices.DirectorySearcher class is not used.
For example: `-CAName "testsrv.test.ch\Test CA"`  Where 'testsrv.test.ch' is the FQDN of your server where the CA is installed on and 'Test CA' is the name of the CA (common name of the CA cert).

Thx,
Jonas

**Comment by poojabaligide** [comment]
hi , the script is working fine, and able create the certificate and export it by providing the complete access.thank you so much

**Comment by J0F3** [comment]
I was actually too fast... 😉
I think I just found by accident what the issue is on PowerShell 4.
@poojabaligide can you please test if it works when you replace the line 303 in the script with the following?:
```powershell
$CAs = (New-Object -TypeName System.DirectoryServices.DirectorySearcher -ArgumentList $searchBase,'objectClass=pKIEnrollmentService').FindAll()
```

Thx

**Comment by poojabaligide** [comment]
I tried with new command , but still there is pop during execution of script to select CA name

**Comment by J0F3** [comment]
Ok, but the error is not shown anymore?
And how many CAs can you select in the pop up? If there are multiple listed then it works as it should.

**Comment by poojabaligide** [comment]
there are 3 CA's in the pop up to select one CA.but I need to resolve this pop up during execution of script...and there is no value set for the attributes comes under pki enrollment services

**Comment by J0F3** [comment]
Then you must use the -CAName parameter to define which CA should be used by the script. This way the pop up is never shown.
For example execute:
```powershell
.\Request-Certificate.ps1 -CN "testing.test.ch" -TemplateName 'TestTemplate' -CAName 'computername.ad.domain.com\CA Name'
```
You can get the FQDN of the computer an the CA Name from the pop up where CA column shows the CA Name and the Computer column show the FQDN.

**Comment by J0F3** [comment]
As I don not hear anything back since a while I assume you do no need further assistance.
So I am going to close that now.
